### ISSUE TITLE
Setup for multiple job brokers

### ISSUE THREAD

**Issue by blootsvoets** [NLeSC/osmium#11]
It would be nice to run osmium as a single service for multiple uses. This means it should be configurable for multiple hosts, instead of the current single host. The user can then choose which host to use (perhaps setting a default host as well). 

Example request:
```
{
    "host": "my.cluster.net",
    "jobdir": "/tmp/jobdir",
    "executable": "/bin/sh",
    ...
}
```

Example job launcher configuration:
```
hosts:
  my.cluster.net:
    scheduler:
      ...
    sandbox:
      ...
    ...
  my.othercluster.net:
    ...
xenon:
  defaultHost: my.cluster.net
http:
  port: 9998
  adminPort: 9998
  bindHost: localhost
```

The `xenon` heading can then be used to set default settings.

**Comment by blootsvoets** [comment]
An alternative request method could be to bind a host to a URL, and keep the request contents the same. For example, the submission URL could be `http://localhost:9998/my.cluster.net` or `http://localhost:9998/` for the default host. The configuration YML would still need to have multiple hosts.

**Comment by sverhoeven** [comment]
I think you want a Xenon scheduler which can run jobs on different hosts. Osmium should make the queue name or resource filter available in it's api.

**Comment by blootsvoets** [comment]
Implemented in fe2966106e28a7e65a55c1237c7f82fe7b65db11. As we discussed, I set it up to not use multiple URLs but to use a single URL, and the user can specify the `scheduler` property. The `joblauncher.yml` supports the `schedulers` and `defaultScheduler` properties. The former is a map of scheduler configurations, the second the name of the default scheduler.

**Comment by sverhoeven** [comment]
The sandbox belongs with scheduler and the new config has not been documentend.

Group scheduler and sandbox together under xenon>launchers
For example:

````
xenon:
  launcher:
    myfirst:
      scheduler:
        scheme: ssh
        location: localhost:22
        queue: multi
      sandbox:
        scheme: ssh
        location: localhost:22
        path: /tmp/jobs
    mysecond:
      scheduler:
        scheme: local
        location: /
        queue: multi
      sandbox:
        scheme: local
        location: /
        path: /tmp/jobs
````
